// In Review Problems
export const FETCH_IN_REVIEW_PROBLEMS_PENDING = "FETCH_IN_REVIEW_PROBLEMS_PENDING"
export const FETCH_IN_REVIEW_PROBLEMS_FULFILLED = "FETCH_IN_REVIEW_PROBLEMS_FULFILLED"
export const FETCH_IN_REVIEW_PROBLEMS_REJECTED = "FETCH_IN_REVIEW_PROBLEMS_REJECTED"
export const UPDATE_IN_REVIEW_PROBLEMS_PENDING = "UPDATE_IN_REVIEW_PROBLEMS_PENDING"
export const UPDATE_IN_REVIEW_PROBLEMS_FULFILLED = "UPDATE_IN_REVIEW_PROBLEMS_FULFILLED"
export const UPDATE_IN_REVIEW_PROBLEMS_REJECTED = "UPDATE_IN_REVIEW_PROBLEMS_REJECTED"

// Review Queue 
export const FETCH_REVIEW_QUEUE_PENDING = "FETCH_REVIEW_QUEUE_PENDING"
export const FETCH_REVIEW_QUEUE_FULFILLED = "FETCH_REVIEW_QUEUE_FULFILLED"
export const FETCH_REVIEW_QUEUE_REJECTED = "FETCH_REVIEW_QUEUE_REJECTED"
export const UPDATE_REVIEW_QUEUE_PENDING = "UPDATE_REVIEW_QUEUE_PENDING" 
export const UPDATE_REVIEW_QUEUE_FULFILLED = "UPDATE_REVIEW_QUEUE_FULFILLED"
export const UPDATE_REVIEW_QUEUE_REJECTED = "UPDATE_REVIEW_QUEUE_REJECTED"

