                                                        
pipeline:

# ████████╗███████╗███████╗████████╗
# ╚══██╔══╝██╔════╝██╔════╝╚══██╔══╝
#    ██║   █████╗  ███████╗   ██║   
#    ██║   ██╔══╝  ╚════██║   ██║   
#    ██║   ███████╗███████║   ██║   
#    ╚═╝   ╚══════╝╚══════╝   ╚═╝   
                                  
  # test:
  #   image: node
  #   commands:
  #     - npm install
  #     - npm install react-scripts@1.1.1 -g
  #     - npm run test

# ██████╗ ██╗   ██╗██╗██╗     ██████╗ 
# ██╔══██╗██║   ██║██║██║     ██╔══██╗
# ██████╔╝██║   ██║██║██║     ██║  ██║
# ██╔══██╗██║   ██║██║██║     ██║  ██║
# ██████╔╝╚██████╔╝██║███████╗██████╔╝
# ╚═════╝  ╚═════╝ ╚═╝╚══════╝╚═════╝ 
                                    
  build:
    image: node
    commands: 
      - npm install
      - npm install react-scripts@1.1.1 -g
      - npm run build

# ██████╗ ██╗   ██╗██████╗ ██╗     ██╗███████╗██╗  ██╗
# ██╔══██╗██║   ██║██╔══██╗██║     ██║██╔════╝██║  ██║
# ██████╔╝██║   ██║██████╔╝██║     ██║███████╗███████║
# ██╔═══╝ ██║   ██║██╔══██╗██║     ██║╚════██║██╔══██║
# ██║     ╚██████╔╝██████╔╝███████╗██║███████║██║  ██║
# ╚═╝      ╚═════╝ ╚═════╝ ╚══════╝╚═╝╚══════╝╚═╝  ╚═╝
                                                    
  publish:
    image: plugins/docker
    repo: brainkeeper/ui
    tags: latest
    when:
      branch: master

# ██████╗  ██████╗ ███╗   ██╗███████╗
# ██╔══██╗██╔═══██╗████╗  ██║██╔════╝
# ██║  ██║██║   ██║██╔██╗ ██║█████╗  
# ██║  ██║██║   ██║██║╚██╗██║██╔══╝  
# ██████╔╝╚██████╔╝██║ ╚████║███████╗
# ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝╚══════╝
                                   