
pipeline:
                                    
  docker_build_push:
    image: plugins/docker
    repo: kurumicode/ui
    tags: latest
    secrets: [ docker_username, docker_password ]
    build_args:
      - REACT_APP_API_HOST=${api_host}
      - REACT_APP_API_PORT=${api_port}
    when:
      branch: master
  
  scp_docker_compose:
    image: appleboy/drone-scp
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    target: /home/junpu/kurumi/ui
    source:
      - docker-compose.yml
    when:
      branch: master


  ssh_docker_down:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/kurumi/ui/docker-compose.yml down
    when:
      branch: master

  ssh_docker_pull:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/kurumi/ui/docker-compose.yml pull
    when:
      branch: master

  ssh_docker_up:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/kurumi/ui/docker-compose.yml up -d
    when:
      branch: master

  ssh_cleanup:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - rm /home/junpu/kurumi/ui/docker-compose.yml
    when:
      branch: master
