
pipeline:
                                    
  docker_build_push:
    image: plugins/docker
    repo: brainkeeper/ui
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  ssh_docker_down:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/brainkeep/ui/docker-compose.yml down

  ssh_docker_pull:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/brainkeep/ui/docker-compose.yml pull

  ssh_docker_up:
    image: appleboy/drone-ssh
    host: 68.47.38.242
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/brainkeep/ui/docker-compose.yml up -d
      