pipeline:

  docker:
    image: plugins/docker
    repo: kurumicode/ui
    tags: latest
    build_args_from_env: [ REACT_APP_API_HOST, REACT_APP_API_PORT ]
    secrets: [ docker_username, docker_password, react_app_api_port, react_app_api_host ]
    when:
      event: [push, tag, deployment]
      branch: master

  scp:
    image: appleboy/drone-scp
    host: kurumi.duckdns.org
    port: 22
    secrets: [ ssh_username, ssh_password ]
    target: /home/junpu/
    source:
      - docker-compose.yml
    when:
      event: [push, tag, deployment]
      branch: master

  down:
    image: appleboy/drone-ssh
    host: kurumi.duckdns.org
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/docker-compose.yml down
    when:
      event: [push, tag, deployment]
      branch: master

  pull:
    image: appleboy/drone-ssh
    host: kurumi.duckdns.org
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/docker-compose.yml pull
    when:
      event: [push, tag, deployment]
      branch: master

  up:
    image: appleboy/drone-ssh
    host: kurumi.duckdns.org
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - /usr/bin/docker-compose -f /home/junpu/docker-compose.yml up -d
    when:
      event: [push, tag, deployment]
      branch: master

  cleanup:
    image: appleboy/drone-ssh
    host: kurumi.duckdns.org
    port: 22
    secrets: [ ssh_username, ssh_password ]
    script:
      - rm -f /home/junpu/docker-compose.yml
    when:
      event: [push, tag, deployment]
      branch: master
