
pipeline:
                                    
  docker:
    image: plugins/docker
    repo: brainkeeper/ui
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
