export const FETCH_IN_REVIEW_PROBLEMS_PATH = "brainkeeper/problem/queued/true/all"
export const UPDATE_IN_REVIEW_PROBLEMS_PATH = "brainkeeper/problem/review"
export const FETCH_REVIEW_QUEUE_PATH = "brainkeeper/review/queue/all"
export const UPDATE_REVIEW_QUEUE_PATH = "brainkeeper/review/queue/one"
export const FETCH_CODER_PATH = "brainkeeper/coder/one"
export const SAVE_NEW_PROBLEM_PATH = "brainkeeper/problem/create"
export const FETCH_PROBLEMS_PATH = "brainkeeper/problem/all"