// In Review Problems
export const FETCH_IN_REVIEW_PROBLEMS_PENDING = "FETCH_IN_REVIEW_PROBLEMS_PENDING"
export const FETCH_IN_REVIEW_PROBLEMS_FULFILLED = "FETCH_IN_REVIEW_PROBLEMS_FULFILLED"
export const FETCH_IN_REVIEW_PROBLEMS_REJECTED = "FETCH_IN_REVIEW_PROBLEMS_REJECTED"
export const UPDATE_IN_REVIEW_PROBLEMS_PENDING = "UPDATE_IN_REVIEW_PROBLEMS_PENDING"
export const UPDATE_IN_REVIEW_PROBLEMS_FULFILLED = "UPDATE_IN_REVIEW_PROBLEMS_FULFILLED"
export const UPDATE_IN_REVIEW_PROBLEMS_REJECTED = "UPDATE_IN_REVIEW_PROBLEMS_REJECTED"

// Review Queue 
export const FETCH_REVIEW_QUEUE_PENDING = "FETCH_REVIEW_QUEUE_PENDING"
export const FETCH_REVIEW_QUEUE_FULFILLED = "FETCH_REVIEW_QUEUE_FULFILLED"
export const FETCH_REVIEW_QUEUE_REJECTED = "FETCH_REVIEW_QUEUE_REJECTED"
export const UPDATE_REVIEW_QUEUE_PENDING = "UPDATE_REVIEW_QUEUE_PENDING" 
export const UPDATE_REVIEW_QUEUE_FULFILLED = "UPDATE_REVIEW_QUEUE_FULFILLED"
export const UPDATE_REVIEW_QUEUE_REJECTED = "UPDATE_REVIEW_QUEUE_REJECTED"

// Coder Info
export const CHANGE_CODER_ACCESS_TOKEN = "CHANGE_CODER_ACCESS_TOKEN"
export const FETCH_CODER_PENDING = "FETCH_CODER_PENDING"
export const FETCH_CODER_FULFILLED = "FETCH_CODER_FULFILLED"
export const FETCH_CODER_REJECTED = "FETCH_CODER_REJECTED"

// AppBar Status
export const OPEN_APPBAR_DIALOG = "OPEN_APPBAR_DIALOG"
export const CLOSE_APPBAR_DIALOG = "CLOSE_APPBAR_DIALOG"

// New Problem
export const CHANGE_NEW_PROBLEM_NAME = "CHANGE_NEW_PROBLEM_NAME"
export const CHANGE_NEW_PROBLEM_URL = "CHANGE_NEW_PROBLEM_URL"
export const SAVE_NEW_PROBLEM_PENDING = "SAVE_NEW_PROBLEM_PENDING"
export const SAVE_NEW_PROBLEM_FULFILLED = "SAVE_NEW_PROBLEM_FULFILLED"
export const SAVE_NEW_PROBLEM_REJECTED = "SAVE_NEW_PROBLEM_REJECTED"

// Problems
export const FETCH_PROBLEMS_PENDING = "FETCH_PROBLEMS_PENDING"
export const FETCH_PROBLEMS_FULFILLED = "FETCH_PROBLEMS_FULFILLED"
export const FETCH_PROBLEMS_REJECTED = "FETCH_PROBLEMS_REJECTED"
