// Input
export const CHANGE_INPUT_TEXT = 'CHANGE_INPUT_TEXT';
export const COMMAND_EXECUTION_BEGIN = 'COMMAND_EXECUTION_BEGIN';
export const COMMAND_EXECUTION_END = 'COMMAND_EXECUTION_END';
export const SET_COMMAND_INVALID = 'SET_COMMAND_INVALID';
export const SET_COMMAND_VALID = 'SET_COMMAND_VALID';

// Add Dialog
export const SET_ADD_DIALOG_OPEN = 'SET_ADD_DIALOG_OPEN';
export const SET_ADD_DIALOG_CLOSE = 'SET_ADD_DIALOG_CLOSE';

// In Review Problems
export const FETCH_IN_REVIEW_PROBLEMS_PENDING = 'FETCH_IN_REVIEW_PROBLEMS_PENDING';
export const FETCH_IN_REVIEW_PROBLEMS_FULFILLED = 'FETCH_IN_REVIEW_PROBLEMS_FULFILLED';
export const FETCH_IN_REVIEW_PROBLEMS_REJECTED = 'FETCH_IN_REVIEW_PROBLEMS_REJECTED';
export const UPDATE_IN_REVIEW_PROBLEMS_PENDING = 'UPDATE_IN_REVIEW_PROBLEMS_PENDING';
export const UPDATE_IN_REVIEW_PROBLEMS_FULFILLED = 'UPDATE_IN_REVIEW_PROBLEMS_FULFILLED';
export const UPDATE_IN_REVIEW_PROBLEMS_REJECTED = 'UPDATE_IN_REVIEW_PROBLEMS_REJECTED';

// Review Queue 
export const FETCH_REVIEW_QUEUE_PENDING = 'FETCH_REVIEW_QUEUE_PENDING';
export const FETCH_REVIEW_QUEUE_FULFILLED = 'FETCH_REVIEW_QUEUE_FULFILLED';
export const FETCH_REVIEW_QUEUE_REJECTED = 'FETCH_REVIEW_QUEUE_REJECTED';
export const UPDATE_REVIEW_QUEUE_PENDING = 'UPDATE_REVIEW_QUEUE_PENDING';
export const UPDATE_REVIEW_QUEUE_FULFILLED = 'UPDATE_REVIEW_QUEUE_FULFILLED';
export const UPDATE_REVIEW_QUEUE_REJECTED = 'UPDATE_REVIEW_QUEUE_REJECTED';

// Coder Info
export const CHANGE_CODER_ACCESS_TOKEN = 'CHANGE_CODER_ACCESS_TOKEN';
export const FETCH_CODER_PENDING = 'FETCH_CODER_PENDING';
export const FETCH_CODER_FULFILLED = 'FETCH_CODER_FULFILLED';
export const FETCH_CODER_REJECTED = 'FETCH_CODER_REJECTED';

// AppBar Status
export const OPEN_HEADER_DIALOG = 'OPEN_HEADER_DIALOG';
export const CLOSE_HEADER_DIALOG = 'CLOSE_HEADER_DIALOG';

// New Question
export const CHANGE_NEW_QUESTION_NAME = 'CHANGE_NEW_QUESTION_NAME';
export const CHANGE_NEW_QUESTION_URL = 'CHANGE_NEW_QUESTION_URL';
export const SAVE_NEW_QUESTION_PENDING = 'SAVE_NEW_QUESTION_PENDING';
export const SAVE_NEW_QUESTION_FULFILLED = 'SAVE_NEW_QUESTION_FULFILLED';
export const SAVE_NEW_QUESTION_REJECTED = 'SAVE_NEW_QUESTION_REJECTED';

// Problems
export const FETCH_PROBLEMS_PENDING = 'FETCH_PROBLEMS_PENDING';
export const FETCH_PROBLEMS_FULFILLED = 'FETCH_PROBLEMS_FULFILLED';
export const FETCH_PROBLEMS_REJECTED = 'FETCH_PROBLEMS_REJECTED';
